### ISSUE TITLE
Allow laravel/slack-notification-channel v2?

### ISSUE THREAD

**Issue by babul** [nathanheffley/laravel-slack-blocks#1]
I'd like to try out your library and blocks with Slack, but have the following issue with a new Laravel 5.8 project with Nova:

composer require nathanheffley/laravel-slack-blocks

Using version ^1.1 for nathanheffley/laravel-slack-blocks
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nathanheffley/laravel-slack-blocks ^1.1 -> satisfiable by nathanheffley/laravel-slack-blocks[1.1.x-dev, v1.1.0, v1.1.1].
    - Can only install one of: laravel/slack-notification-channel[1.0.x-dev, v2.0.0].
    - Can only install one of: laravel/slack-notification-channel[v2.0.0, 1.0.x-dev].
    - Can only install one of: laravel/slack-notification-channel[1.0.x-dev, v2.0.0].
    - Conclusion: install laravel/slack-notification-channel 1.0.x-dev
    - Installation request for laravel/slack-notification-channel (locked at v2.0.0, required as ^2.0) -> satisfiable by laravel/slack-notification-channel[v2.0.0].

I'd appreciate any assistance. Thanks!

**Comment by nathanheffley** [comment]
Looks like this package needs a v2 release that updates to v2 of the core slack notification package :+1:

**Comment by nathanheffley** [comment]
Can you test out using the `dev-master` branch to see if that works? If so, I'll release that it as v2.

**Comment by nathanheffley** [comment]
@babul can you test out using the dev-master branch to see if that works? If so, I'll release that it as v2.

**Comment by babul** [comment]
Nathan - dev-master works! Thanks so much for the fast response :D

**Comment by nathanheffley** [comment]
Great! I've tagged it as v2.0.0 so you'll want to update your project to use that release.
