### ISSUE TITLE
Slack message seems to be "preview"

### ISSUE THREAD

**Issue by Hesesses** [nathanheffley/laravel-slack-blocks#15]
When sending a message to slack, it seems to be "preview" (see the gray bar next to hello world)

![image](https://user-images.githubusercontent.com/2721970/111686151-638ea580-8831-11eb-8db1-b9b2d2d8835b.png)

When posting a longer message, it shows see more at the bottom and the message is not fully shown... Do you have any ideas how to fix this?

My code:

```
return (new SlackMessage)
            ->from($name, $icon)
            ->to('#testing')
            ->attachment(function ($attachment) {
                $attachment->block(function ($block) {
                    $block
                        ->type('section')
                        ->text([
                            'type' => 'mrkdwn',
                            'text' => '*Hello World!*',
                        ]);
                });
            });
```

**Comment by nathanheffley** [comment]
Instead of using the `attachment` function you should be able to use the `block` function (which operates in a similar fashion).

I realize now that the readme only demonstrates the attachment function which I'll have to rectify.

Let me know if the `block` function works for you.

**Comment by Hesesses** [comment]
Thank you for the fast reply. It works now 🙏
