### ISSUE TITLE
About the maximum number of blocks

### ISSUE THREAD

**Issue by adachi-tatsuru** [nathanheffley/laravel-slack-blocks#19]
Valid number of block items as JSON in Block Kit is "50". Post errors like Invalid_Item will be returned if you notify more than 50 items.

**Comment by nathanheffley** [comment]
Hello @adachi-tatsuru, thanks for filing this issue! What error do you receive if you try sending a message with more than 50 block items?

I am hesitant to do anything about this as Slack may increase or decrease that limit in the future.

**Comment by adachi-tatsuru** [comment]
## Headers

```
    Status Code: 400 Bad Request
    access-control-allow-origin: *
    content-type: text/html
    date: Sun, 02 Oct 2022 01:28:44 GMT
    referrer-policy: no-referrer
    server: Apache
    strict-transport-security: max-age=31536000; includeSubDomains; preload
    via: envoy-www-iad-k968, envoy-edge-nrt-gq16
    x-backend: main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow
    x-edge-backend: envoy-www
    x-envoy-upstream-service-time: 166
    x-firefox-spdy: h2
    x-frame-options: SAMEORIGIN
    x-powered-by: HHVM/4.153.1
    x-server: slack-www-hhvm-main-iad-nied
    x-slack-backend: r
    x-slack-edge-shared-secret-outcome: no-match
    x-slack-shared-secret-outcome: no-match
    x-slack-unique-id: xxxxx
```

## Response

```
invalid_blocks
```

## Features I want you to create

I thought it would be nice to have a function that allows you to set a limit for block items, and if the limit is exceeded, you can split it and send it.

**Comment by adachi-tatsuru** [comment]
# [Reference: Layout blocks](https://api.slack.com/reference/block-kit/blocks)

> Read our guide to building block layouts to learn where and how to use each of these components. You can include up to 50 blocks in each message, and 100 blocks in modals or home tabs.

**Comment by nathanheffley** [comment]
From my understanding of the API, splitting a message with blocks into multiple messages could cause issues if you plan on responding to a button click or other interactive part of the message.

I think this functionality is something that developers should understand and handle, especially considering 50 blocks in one message seems like a limit so high that most projects won't ever have to worry about it. This library is a bare minimum implementation of using the Blocks API. I never plan to add validation that the blocks you're sending are formatted correctly beyond what the library does already, and this falls into that category for me.
