### ISSUE TITLE
Does this package also support "type": "context"?

### ISSUE THREAD

**Issue by jtomek** [nathanheffley/laravel-slack-blocks#3]
Hello, a good job with this package. Everything works fine, except maybe it's my lack of understanding of the inner workings - does this package supports type context? You code recognizes "elements", but I can't get it to work for type:context. Can you please help?

Slack Blocks example that I can't get to work:

```
{
  "type": "context",
  "elements": [{
      "type": "image",
      "image_url": "https://api.slack.com/img/blocks/bkb_template_images/tripAgentLocationMarker.png",
      "alt_text": "Location Pin Icon"
    },
    {
      "type": "plain_text",
      "emoji": true,
      "text": "Location: Central Business District"
    }
  ]
}
```

My simple attempt:

```
$attachment->block(function ($block) use ($item) {
  $block
      ->type('context')
      ->elements([
          'type' => 'plain_text',
          'text' => 'text'
      ]);
});

```

**Comment by jtomek** [comment]
Ok, I just figured it out. "Elements" needs an array of objects. One pair of brackets was missing. :)

```
$attachment->block(function ($block) use ($item) {
  $block
      ->type('context')
      ->elements([[
          'type' => 'plain_text',
          'text' => 'text'
      ]]);
});

```

**Comment by nathanheffley** [comment]
I'm glad you were able to figure it out, I'll look into making sure the documentation is as clear as possible around this issue 👍
