### ISSUE TITLE
Undefined property: Illuminate\Notifications\Messages\SlackMessage::$blocks

### ISSUE THREAD

**Issue by aarondfrancis** [nathanheffley/laravel-slack-blocks#5]
Hey there, 

Thanks for making this great library. We started using it yesterday and it's made our slack notifications much more customizable.

We're currently running into an error sending a slack message that *we don't control*. Specifically, Horizon sends the `LongWaitDetected` message through slack. Since we don't control that, it's a standard `SlackMessage` instead of one of the new ones with the `blocks` property.

That means that when your code gets to [this line](https://github.com/nathanheffley/laravel-slack-blocks/blob/2.0/src/Channels/SlackWebhookChannel.php#L93), it dies because `blocks` is not defined on the base `SlackMessage`.

Can we add a `property_exists` check for that property?

Thanks!

**Comment by nathanheffley** [comment]
Great catch, since you're working with it right now could you open up a PR for it with a test? I'll make sure it gets merged in ASAP for you.

**Comment by aarondfrancis** [comment]
Done!
