### ISSUE TITLE
Noticed an issue with trying to assign a url

### ISSUE THREAD

**Issue by jhavenz** [nathanheffley/laravel-slack-blocks#7]
Theres a typo in the 'SlackBlock.php' file, where assigning the url. Kinda drove me batty for a while until I found it.
Starting at line 144, you have:

/**
     * Set the url of the block.
     *
     * @param  string  $url
     * @return $this
     */
    public function url($url)
    {
        $this->$url = $url; 

        return $this;
    }

$this->$url = $url; 

Should be :
$this->url = $url

Note For Those Attempting To Add Multiple Blocks and/or use action buttons. I just spent a good 2 hours troubleshooting how to do these things...so maybe itll help someone else who sees this. This is working code for multiple blocks and using an "actions" button:

```php

(new SlackMessage)
            ->error()
            ->attachment(function ($attachment) {
                  $attachment->block(function ($block) {
                      $block
                          ->type('section')
                          ->text([
                              'type' => 'mrkdwn',
                              'text' => 'hello world',
                          ]);
                  });
                  $attachment->block(function ($block) {
                      $block
                          ->type('actions')
                          ->elements([[
                              'type' => 'button',
                              'text' => [
                                  'type' => 'plain_text',
                                  'text' => 'Google Home Page',
                              ],
                              'url' => "https://google.com"
                          ]]);
                  });
            });
```

**Comment by nathanheffley** [comment]
Oh man, that's not good 😅

Would you be able to open a PR to remove the `$`?
