### ISSUE TITLE
Please update guzzlehttp/guzzle to v7.0.1

### ISSUE THREAD

**Issue by webdevnerdstuff** [nathanheffley/laravel-slack-blocks#9]
**Problem**
With Laravel 8 Update, they have you update Guzzle to Version 7.0.1. This the problem that occurs"
https://laravel.com/docs/8.x/upgrade#updating-dependencies

>   Problem 1
    - Installation request for nathanheffley/laravel-slack-blocks ^2.2 -> satisfiable by nathanheffley/laravel-slack-blocks[v2.2.0, v2.2.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.0.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[7.1.x-dev, 6.5.x-dev].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle ^7.0.1 -> satisfiable by guzzlehttp/guzzle[7.0.1, 7.0.x-dev, 7.1.x-dev].

**Solution**
Please update Composer package guzzlehttp/guzzle to v7.0.1. Thank you.

**Comment by nathanheffley** [comment]
Hey @webdevnerdstuff, thank you for pointing this out! v2.2.2 should fix the dependency issue.

**Comment by webdevnerdstuff** [comment]
Tested install with my Laravel 8 Upgraded site and worked no problem. Tested the slack notification it's using and it is also working as it should. Thanks for the quick response and update.
